CREATE TABLE "JUDGE_TEST_CASES"
(
  "ID"          NUMBER NOT NULL ENABLE,
  "PROBLEM_ID"  NUMBER NOT NULL ENABLE,
  "DESCRIPTION" CLOB,
  "INPUT"       CLOB   NOT NULL ENABLE,
  "OUTPUT"      CLOB   NOT NULL ENABLE,
  CONSTRAINT "JUDGE_TEST_CASES_PK" PRIMARY KEY ("ID") ENABLE
);
ALTER TABLE "JUDGE_TEST_CASES" ADD CONSTRAINT "JUDGE_TEST_CASES_CON" FOREIGN KEY ("PROBLEM_ID")
REFERENCES "JUDGE_PROBLEMS" ("ID") ENABLE;

CREATE OR REPLACE TRIGGER "BI_JUDGE_TEST_CASES"
BEFORE INSERT ON "JUDGE_TEST_CASES"
FOR EACH ROW
  BEGIN
    IF :NEW."ID" IS NULL
    THEN
      SELECT "JUDGE_TEST_CASES_SEQ".nextval
      INTO :NEW."ID"
      FROM dual;
    END IF;
  END;

/
ALTER TRIGGER "BI_JUDGE_TEST_CASES" ENABLE;