CREATE TABLE  "JUDGE_TEST_CASES"
(	"ID" NUMBER NOT NULL ENABLE,
   "PROBLEM_ID" NUMBER NOT NULL ENABLE,
   "DESCRIPTION" CLOB,
   "INPUT" CLOB NOT NULL ENABLE,
   "OUTPUT" CLOB NOT NULL ENABLE,
  CONSTRAINT "JUDGE_TEST_CASES_PK" PRIMARY KEY ("ID") ENABLE
) ;ALTER TABLE  "JUDGE_TEST_CASES" ADD CONSTRAINT "JUDGE_TEST_CASES_CON" FOREIGN KEY ("PROBLEM_ID")
REFERENCES  "JUDGE_PROBLEMS" ("ID") ENABLE;

CREATE OR REPLACE TRIGGER  "BI_JUDGE_TEST_CASES"
before insert on "JUDGE_TEST_CASES"
for each row
  begin
    if :NEW."ID" is null then
      select "JUDGE_TEST_CASES_SEQ".nextval into :NEW."ID" from dual;
    end if;
  end;

/
ALTER TRIGGER  "BI_JUDGE_TEST_CASES" ENABLE;