CREATE TABLE "JUDGE_SUBCATEGORIES"
(
  "ID"          NUMBER        NOT NULL ENABLE,
  "SUBCATEGORY" VARCHAR2(255) NOT NULL ENABLE,
  "DESCRIPTION" VARCHAR2(255),
  CONSTRAINT "JUDGE_SUBCATEGORIES_PK" PRIMARY KEY ("ID") ENABLE,
  CONSTRAINT "JUDGE_SUBCATEGORIES_UK1" UNIQUE ("SUBCATEGORY") ENABLE
);

CREATE OR REPLACE TRIGGER "BI_JUDGE_SUBCATEGORIES"
BEFORE INSERT ON "JUDGE_SUBCATEGORIES"
FOR EACH ROW
  BEGIN
    IF :NEW."ID" IS NULL
    THEN
      SELECT "JUDGE_SUBCATEGORIES_SEQ".nextval
      INTO :NEW."ID"
      FROM dual;
    END IF;
  END;

/
ALTER TRIGGER "BI_JUDGE_SUBCATEGORIES" ENABLE;