CREATE TABLE "JUDGE_USERS"
(
	"ID"         NUMBER       NOT NULL ENABLE,
	"USERNAME"   VARCHAR2(20) NOT NULL ENABLE,
	"PASSWORD"   VARCHAR2(32) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"LAST_NAME"  VARCHAR2(50) NOT NULL ENABLE,
	"ROLE"       VARCHAR2(10),
	"IN_Z"       TIMESTAMP(6),
	"OUT_Z"      TIMESTAMP(6),
	"LOGGED_IN"  CHAR(1),
	CONSTRAINT "JUDGE_USERS_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "JUDGE_USERS_UK1" UNIQUE ("USERNAME") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER "BI_JUDGE_USERS"
BEFORE INSERT ON "JUDGE_USERS"
FOR EACH ROW
	BEGIN
		IF :NEW."ID" IS NULL
		THEN
			SELECT "JUDGE_USERS_SEQ".nextval
			INTO :NEW."ID"
			FROM dual;
		END IF;
	END;

/
ALTER TRIGGER  "BI_JUDGE_USERS" ENABLE;