CREATE TABLE  "JUDGE_USERS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"USERNAME" VARCHAR2(20) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(32) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"ROLE" VARCHAR2(10),
	"IN_Z" TIMESTAMP (6),
	"OUT_Z" TIMESTAMP (6),
	 CONSTRAINT "JUDGE_USERS_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "JUDGE_USERS_UK1" UNIQUE ("USERNAME") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "BI_JUDGE_USERS"
  before insert on "JUDGE_USERS"
  for each row
begin
  if :NEW."ID" is null then
    select "JUDGE_USERS_SEQ".nextval into :NEW."ID" from dual;
  end if;
end;

/
ALTER TRIGGER  "BI_JUDGE_USERS" ENABLE;